name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY NAME:
    description: "Who to greet"
    required: True
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
